# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
