# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 06:57
from __future__ import unicode_literals

import competitions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('logo', models.ImageField(upload_to=competitions.models.generate_image_upload_path)),
                ('image', models.ImageField(upload_to=competitions.models.generate_image_upload_path)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('status', models.IntegerField(choices=[(1, b'Inactivate'), (2, b'Activate')], default=1)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to=competitions.models.generate_data_upload_path)),
                ('type', models.IntegerField(choices=[(1, b'Training'), (2, b'Testing')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='competitions.Competition')),
            ],
        ),
    ]
