# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20160912_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='short_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
