# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20160913_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiondata',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
