# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20161012_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='short_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='short_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
