# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20161013_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='short_title',
        ),
    ]
