# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_remove_competition_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='short_description',
            field=models.TextField(),
        ),
    ]
