# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20161018_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, b'----------'), (1, b'Supervised'), (2, b'Unsupervised'), (3, b'Reinforcement Learning')], default=0),
            preserve_default=False,
        ),
    ]
