# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20161018_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiondata',
            name='type',
            field=models.IntegerField(choices=[(1, b'X Train'), (2, b'Y Train'), (3, b'X Test'), (4, b'Y Test')], default=0),
        ),
    ]
