# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 06:45
from __future__ import unicode_literals

import competitions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_submission_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=competitions.models.generate_evaluation_upload_path)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='competitions.Competition')),
            ],
        ),
    ]
