# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0016_evaluationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[(b'stripe', b'Stripe'), (b'paypal', b'PayPal')], max_length=10)),
                ('paymentID', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, b'Inprogress'), (2, b'Failed'), (3, b'Completed')])),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('message_log', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='competitions.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
