# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcode',
            name='evaluation_func',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationcode',
            name='validation_func',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
