# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20161124_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='message_log',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, b'Success'), (2, b'Error')], default=1),
        ),
    ]
