# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_submission_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(1, b'Inactivate'), (2, b'Incoming'), (3, b'Activate'), (4, b'Finished')], default=1),
        ),
    ]
