# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_auto_20161207_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('place', models.IntegerField(choices=[(1, b'1st place'), (2, b'2nd place'), (3, b'3rd place'), (4, b'4th place'), (5, b'5th place')])),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='competitions.Competition')),
            ],
        ),
    ]
