# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 11:05
from __future__ import unicode_literals

import competitions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_auto_20161219_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=competitions.models.generate_topic_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='competitions.ForumTopic')),
            ],
        ),
    ]
