# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_auto_20170215_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcode',
            name='message_log',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
